version: "3.9"
services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "qwerty"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
  
  nats:
    image: nats:alpine
    ports:
      - "4222:4222"
      - "8222:8222"
    command: -js
    restart: unless-stopped