// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Cache is an autogenerated mock type for the Cache type
type Cache[KeyT comparable, ValueT interface{}] struct {
	mock.Mock
}

// Get provides a mock function with given fields: key
func (_m *Cache[KeyT, ValueT]) Get(key KeyT) (ValueT, bool) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 ValueT
	var r1 bool
	if rf, ok := ret.Get(0).(func(KeyT) (ValueT, bool)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(KeyT) ValueT); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(ValueT)
	}

	if rf, ok := ret.Get(1).(func(KeyT) bool); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// Put provides a mock function with given fields: key, value
func (_m *Cache[KeyT, ValueT]) Put(key KeyT, value ValueT) {
	_m.Called(key, value)
}

// NewCache creates a new instance of Cache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCache[KeyT comparable, ValueT interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *Cache[KeyT, ValueT] {
	mock := &Cache[KeyT, ValueT]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
